version: 2.1

orbs:
  win: circleci/windows@2.2.0

commands:
  checkout-and-yarn-install:
    steps:
      - checkout
      - &yarn-versions
        run:
          name: Versions
          command: yarn versions
      - &restore-yarn-cache
        restore_cache:
          key: yarn-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package.json" }}
      - &yarn-install
        run:
          name: Install dependencies
          command: yarn install --ignore-engines
      - &save-yarn-cache
        save_cache:
          key: yarn-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ./yarn.lock

prebuild-linux-base: &prebuild-linux-base
  docker:
    # from node:10.0.0 on 2021-08-30
    # glibc needs to be old enough for older distros
    - image: node@sha256:4013aa6c297808defd01234fce4a42e1ca0518a5bd0260752a86a46542b38206
  working_directory: ~/dd-native-metrics-js
  resource_class: small
  steps:
    - checkout-and-yarn-install
    - &yarn-prebuild
      run:
        name: Compile prebuilt binaries
        command: yarn prebuild
    - &persist-prebuilds
      persist_to_workspace:
        root: ~/dd-native-metrics-js
        paths:
          - prebuilds

prebuild-linux-ia32-base: &prebuild-linux-ia32-base
  <<: *prebuild-linux-base
  steps:
    - run:
        name: Install job dependencies
        command: apt-get update && apt-get install -y g++-multilib
    - checkout-and-yarn-install
    - *yarn-prebuild
    - *persist-prebuilds

test-prebuild-linux-base: &test-prebuild-linux-base
  docker:
    - image: node:slim
  working_directory: ~/dd-native-metrics-js
  resource_class: small
  steps:
    - checkout-and-yarn-install
    - attach_workspace:
        at: ~/dd-native-metrics-js
    - &yarn-test
      run:
        name: Unit tests
        command: yarn test

prebuild-darwin-base: &prebuild-darwin-base
  macos:
    xcode: "12.2.0"
  working_directory: ~/dd-native-metrics-js
  steps:
    - checkout-and-yarn-install
    - *yarn-prebuild
    - *yarn-test
    - *persist-prebuilds

prebuild-win32-base: &prebuild-win32-base
  executor:
    name: win/default
    size: medium
  working_directory: ~/dd-native-metrics-js
  steps:
    - checkout-and-yarn-install
    - *yarn-prebuild
    - *yarn-test
    - *persist-prebuilds

jobs:
  # Linting

  lint:
    docker:
      - image: node
    working_directory: ~/dd-native-metrics-js
    resource_class: small
    steps:
      - checkout-and-yarn-install
      - run:
          name: Lint
          command: yarn lint

  # Prebuilds (linux x64)

  linux-x64-16:
    <<: *prebuild-linux-base
    docker:
      # from node:12.0.0 on 2021-08-30
      - image: node@sha256:c88ef4f7ca8d52ed50366d821e104d029f43e8686120a29541ce0371f333453f
    environment:
      - ARCH=x64
      - NODE_VERSIONS=15 - 17

  linux-x64-12:
    <<: *prebuild-linux-base
    environment:
      - ARCH=x64
      - NODE_VERSIONS=12 - 14

  ## Tests

  linux-x64-latest-test:
    <<: *test-prebuild-linux-base
    docker:
      - image: node

  linux-x64-16-test:
    <<: *test-prebuild-linux-base
    docker:
      - image: node:16

  linux-x64-14-test:
    <<: *test-prebuild-linux-base
    docker:
      - image: node:14

  linux-x64-12-test:
    <<: *test-prebuild-linux-base
    docker:
      - image: node:12

  alpine-x64-latest-test:
    <<: *test-prebuild-linux-base
    docker:
      - image: node:alpine

  alpine-x64-16-test:
    <<: *test-prebuild-linux-base
    docker:
      - image: node:16-alpine

  alpine-x64-14-test:
    <<: *test-prebuild-linux-base
    docker:
      - image: node:14-alpine

  alpine-x64-12-test:
    <<: *test-prebuild-linux-base
    docker:
      - image: node:12-alpine

  # Prebuilds (alpine x64)

  alpine-x64: &alpine-base
    docker:
      # from node:alpine on 2021-08-30
      - image: node@sha256:1ee1478ef46a53fc0584729999a0570cf2fb174fbfe0370edbf09680b2378b56
    working_directory: ~/dd-native-metrics-js
    resource_class: small
    steps:
      - run:
          name: Install job dependencies
          command: apk add g++ git make python3
      - checkout-and-yarn-install
      - &yarn-rebuild
          run:
            name: Compile native code
            command: yarn rebuild
      - *yarn-test

  # Prebuilds (alpine ia32)

  alpine-ia32:
    <<: *alpine-base
    docker:
      # from i386/node:alpine on 2021-08-30
      - image: i386/node@sha256:c81d659f51a11aea6d73598fce064cf087b21caf9046fbf34530d9f1d43c8ec8

  # Prebuilds (linux ia32)

  linux-ia32-12:
    <<: *prebuild-linux-ia32-base
    environment:
      - ARCH=ia32
      - NODE_VERSIONS=12 - 13

  ## Tests

  linux-ia32-13-test:
    <<: *test-prebuild-linux-base
    docker:
      - image: i386/node:13-alpine

  linux-ia32-12-test:
    <<: *test-prebuild-linux-base
    docker:
      - image: i386/node:12-alpine

  # Prebuilds (darwin)

  macos:
    <<: *prebuild-darwin-base
    environment:
      - ARCH=ia32,x64
      - NODE_VERSIONS=12 - 17

  # Prebuilds (win32)

  windows:
    <<: *prebuild-win32-base
    environment:
      - ARCH=ia32,x64
      - NODE_VERSIONS=12 - 17

  # Prebuild Artifacts

  prebuilds:
    docker:
      - image: node
    working_directory: ~/dd-native-metrics-js
    resource_class: small
    steps:
      - checkout-and-yarn-install
      - attach_workspace:
          at: ~/dd-native-metrics-js
      - run:
          name: Create prebuilds archive
          command: yarn prebuilds
      - store_artifacts:
          path: ./prebuilds.tgz
      - store_artifacts:
          path: ./prebuilds.tgz.sha256

workflows:
  version: 2
  build:
    jobs: &jobs
      # Linux x64
      - linux-x64-16
      - linux-x64-12
      - linux-x64-latest-test:
          requires:
            - linux-x64-16
      - linux-x64-16-test:
          requires:
            - linux-x64-16
      - linux-x64-14-test:
          requires:
            - linux-x64-12
      - linux-x64-12-test:
          requires:
            - linux-x64-12
      - alpine-x64-latest-test:
          requires:
            - linux-x64-16
      - alpine-x64-16-test:
          requires:
            - linux-x64-16
      - alpine-x64-14-test:
          requires:
            - linux-x64-12
      - alpine-x64-12-test:
          requires:
            - linux-x64-12
      # Linux ia32
      - linux-ia32-12
      - linux-ia32-13-test:
          requires:
            - linux-ia32-12
      - linux-ia32-12-test:
          requires:
            - linux-ia32-12
      - alpine-x64
      - alpine-ia32
      - macos
      - windows
      - prebuilds:
          requires:
            - linux-x64-latest-test
            - linux-x64-16-test
            - linux-x64-14-test
            - linux-x64-12-test
            - linux-ia32-13-test
            - linux-ia32-12-test
            - alpine-x64-latest-test
            - alpine-x64-16-test
            - alpine-x64-14-test
            - alpine-x64-12-test
            - macos
            - windows
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs: *jobs
