runs:
  using: composite
  steps:
    - uses: ./.github/actions/yarn
    - run: yarn prebuild
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: prebuilds
        path: prebuilds/**/*
