inputs:
  runs-on:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - run: yarn versions
    - uses: actions/cache@v2
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('package.json') }}
    - run: yarn install --ignore-engines
      if: steps.cache.outputs.cache-hit != 'true'
    - run: yarn prebuild
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ github.run_id }}
        path: prebuilds/**/*
