issuer: https://token.actions.githubusercontent.com

subject: repo:DataDog/dd-native-metrics-js:environment:npm

claim_pattern:
  event_name: push
  job_workflow_ref: DataDog/dd-native-metrics-js/\.github/workflows/release\.yml@refs/heads/v[0-9]+\.x
  ref: refs/heads/v[0-9]+\.x
  repository: DataDog/dd-native-metrics-js

permissions:
  contents: write
