name: Build

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linux:
    strategy:
      matrix:
        arch: ['ia32', 'x64']
    runs-on: ubuntu-latest
    container:
      # using oldest image to ensure support for older glibc
      # from node:12.0.0 on 2021-08-30
      image: node@sha256:c88ef4f7ca8d52ed50366d821e104d029f43e8686120a29541ce0371f333453f
    name: linux-${{ matrix.arch }}
    env:
      ARCH: ${{ matrix.arch }}
    steps:
      - run: apt-get update && apt-get install -y g++-multilib
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prebuild

  macos-apple:
    runs-on: macos-11
    name: macos-apple
    env:
      ARCH: arm64
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prebuild

  macos-intel:
    strategy:
      matrix:
        arch: ['ia32', 'x64']
    runs-on: macos-10.15
    name: macos-intel-${{ matrix.arch }}
    env:
      ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prebuild

  windows:
    strategy:
      matrix:
        arch: ['ia32', 'x64']
    runs-on: windows-2019
    name: windows-${{ matrix.arch }}
    env:
      ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prebuild

  # Tests

  alpine-test:
    strategy:
      matrix:
        node: [12, 14, 16, 18]
    needs: linux
    runs-on: ubuntu-latest
    container:
      image: node:${{ matrix.node }}-alpine
    name: alpine-test-${{ matrix.node }}
    steps:
      - run: apk update && apk add bash
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test

  linux-test:
    needs: linux
    runs-on: ubuntu-latest
    name: linux-test-${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/node/12
      - uses: ./.github/actions/test
      - uses: ./.github/actions/node/14
      - uses: ./.github/actions/test
      - uses: ./.github/actions/node/16
      - uses: ./.github/actions/test
      - uses: ./.github/actions/node/18
      - uses: ./.github/actions/test

  macos-intel-test:
    needs: macos-intel
    runs-on: macos-10.15
    name: macos-intel-test-${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/node/12
      - uses: ./.github/actions/test
      - uses: ./.github/actions/node/14
      - uses: ./.github/actions/test
      - uses: ./.github/actions/node/16
      - uses: ./.github/actions/test
      - uses: ./.github/actions/node/18
      - uses: ./.github/actions/test

  windows-test:
    needs: windows
    runs-on: windows-2019
    name: windows-test-${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/node/12
      - uses: ./.github/actions/test
      - uses: ./.github/actions/node/14
      - uses: ./.github/actions/test
      - uses: ./.github/actions/node/16
      - uses: ./.github/actions/test
      - uses: ./.github/actions/node/18
      - uses: ./.github/actions/test
