on: push
jobs:
  linux:
    strategy:
      matrix:
        arch: ['ia32', 'x64']
    runs-on: ubuntu-latest
    container:
      # using oldest image to ensure support for older glibc
      # from node:12.0.0 on 2021-08-30
      image: node@sha256:c88ef4f7ca8d52ed50366d821e104d029f43e8686120a29541ce0371f333453f
    name: linux-${{ matrix.arch }}
    env:
      ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v2
      - run: apt-get update && apt-get install -y g++-multilib
      - uses: ./.github/actions/prebuild

  linux-ia32-test:
    strategy:
      matrix:
        node: [12]
    needs: linux
    runs-on: ubuntu-latest
    name: linux-ia32-test-${{ matrix.node }}
    container:
      image: i386/node:${{ matrix.node }}-alpine
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: prebuilds
      - run: rm binding.gyp
      - uses: ./.github/actions/yarn
      - run: yarn test

  linux-x64-test:
    strategy:
      matrix:
        node: [12, 14, 16, 17]
    needs: linux
    runs-on: ubuntu-latest
    name: linux-x64-test-${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - run: rm binding.gyp
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - uses: actions/download-artifact@v2
        with:
          path: prebuilds
      - run: yarn test

  macos-apple:
    runs-on: macos-11
    name: macos-apple
    env:
      ARCH: arm64
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prebuild

  macos-intel:
    strategy:
      matrix:
        arch: ['ia32', 'x64']
    runs-on: macos-10.15
    name: macos-intel-${{ matrix.arch }}
    env:
      ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prebuild

  macos-intel-test:
    strategy:
      matrix:
        arch: ['ia32', 'x64']
    runs-on: macos-10.15
    name: macos-intel-test-node-${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - run: rm binding.gyp
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - run: yarn test

  windows:
    strategy:
      matrix:
        arch: ['ia32', 'x64']
    runs-on: windows-2019
    name: windows-${{ matrix.arch }}
    env:
      NODE_VERSIONS: ${{ matrix.node }}
      ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prebuild

  windows-test:
    strategy:
      matrix:
        node: [12, 14, 16, 17]
    runs-on: windows-2019
    name: windows-test-node-${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - run: rm binding.gyp
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - run: yarn test
