on: push
jobs:
  linux-x86:
    runs-on: ubuntu-latest
    container:
      # using oldest image to ensure support for older glibc
      # from node:12.0.0 on 2021-08-30
      image: node@sha256:c88ef4f7ca8d52ed50366d821e104d029f43e8686120a29541ce0371f333453f
    name: Linux x86-64
    steps:
      - uses: actions/checkout@v2
      - run: yarn versions
      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package.json') }}
      - run: yarn install --ignore-engines
        if: steps.cache.outputs.cache-hit != 'true'
      - run: yarn prebuild
