on: push
jobs:
  linux:
    strategy:
      matrix:
        arch: ['ia32', 'x64']
    runs-on: ubuntu-latest
    container:
      # using oldest image to ensure support for older glibc
      # from node:12.0.0 on 2021-08-30
      image: node@sha256:c88ef4f7ca8d52ed50366d821e104d029f43e8686120a29541ce0371f333453f
    name: linux-${{ matrix.arch }}
    env:
      ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prebuild

  macos-apple:
    runs-on: macos-11
    name: macos-apple
    env:
      ARCH: arm64
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prebuild

  macos-intel:
    strategy:
      matrix:
        arch: ['ia32', 'x64']
    runs-on: macos-10.15
    name: macos-intel-${{ matrix.arch }}
    env:
      ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prebuild

  windows:
    strategy:
      matrix:
        arch: ['ia32', 'x64']
        node: [12, 13, 14, 15, 16, 17] # VC++ is slow, split by Node version
    runs-on: windows-2019
    name: windows-${{ matrix.arch }}-node-${{ matrix.node }}
    env:
      NODE_VERSIONS: ${{ matrix.node }}
      ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prebuild
