name: Build

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:
    uses: Datadog/action-prebuildify/.github/workflows/build.yml@main
    with:
      target-name: 'metrics'
      package-manager: 'yarn'
      cache: true
