name: Build + Publish

on:
  push:
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:
    uses: ./.github/workflows/build.yml
  publish:
    uses: ./.github/workflows/publish.yml
    if: ${{ contains(['v1.x'], github.ref_name) }}
    needs: [build]
    # secrets:
    #   npm_token: ${{ env.NPM_TOKEN }}
