on: push
jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      # using oldest image to ensure support for older glibc
      # from node:12.0.0 on 2021-08-30
      image: node@sha256:c88ef4f7ca8d52ed50366d821e104d029f43e8686120a29541ce0371f333453f
    name: Linux
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prebuild

  windows:
    runs-on: windows-2019
    name: Windows
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prebuild

  prebuilds:
    runs-on: ubuntu-latest
    needs: ['linux', 'windows']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('package.json') }}
      - run: yarn install --ignore-engines
        shell: bash
        if: steps.cache.outputs.cache-hit != 'true'
      - uses: actions/download-artifact@v2
        with:
          path: ${{ runner.temp }}/prebuilds
      - run: mv $RUNNER_TEMP/prebuilds/* prebuilds
      - run: yarn prebuilds
      - uses: actions/upload-artifact@v2
        with:
          name: prebuilds
          path: prebuilds/**/*
