jobs:
  linux-x86:
    runs-on: ubuntu-latest
    container:
      # from node:12.0.0 on 2021-08-30
      image: node@sha256:c88ef4f7ca8d52ed50366d821e104d029f43e8686120a29541ce0371f333453f
    name: Linux x86-64
    steps:
      - run: yarn versions
      # TODO: cache
      - run: yarn install --ignore-engines
      - run: yarn prebuild
