name: Build

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:
    uses: Datadog/action-prebuildify/.github/workflows/build.yml@main
    with:
      target-name: 'metrics'
      package-manager: 'yarn'
      cache: true
      min-node-version: 16
      napi: true

  package-size:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - run: yarn
      - name: Compute module size tree and report
        uses: qard/heaviest-objects-in-the-universe@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
