name: Pull Request Labels

on:
  pull_request_target:
    types: [opened, labeled, unlabeled, synchronize]
    branches:
      - main

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@d2892166405e47deea29d2052ab4cca1382df41e # v1.2.0
        with:
          mode: exactly
          count: 1
          labels: "semver-patch, semver-minor, semver-major"
