name: Publish

on:
  # push:
  # schedule:
  #   - cron: '0 4 * * *'
  workflow_call:
    # secrets:
    #   npm_token:
    #     required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    name: publish
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - run: yarn
      - run: ls -lisa prebuilds
