name: Release

on:
  push:
    branches:
      - v[0-9]+.x

jobs:
  build:
    uses: Datadog/action-prebuildify/.github/workflows/build.yml@main
    with:
      target-name: 'metrics'
      package-manager: 'yarn'
      cache: true
      min-node-version: 14
      napi: true

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment: npm
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish
      - id: pkg
        run: |
          content=`cat ./package.json | tr '\n' ' '`
          echo "json=$content" >> "$GITHUB_OUTPUT"
      - run: |
          git tag v${{ fromJson(steps.pkg.outputs.json).version }}
          git push origin v${{ fromJson(steps.pkg.outputs.json).version }}
