name: Release

on:
  workflow_call:
    secrets:
      npm_token:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm
    secrets:
      npm_token: ${{ env.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - run: ls -lisa prebuilds
