name: Release

on:
  push:
    branches:
      - v[0-9]+.x

jobs:
  build:
    uses: Datadog/action-prebuildify/.github/workflows/build.yml@d4e89247e6dd34f485c0f92c12f0cc739c2f8c92 # main
    with:
      target-name: 'metrics'
      package-manager: 'yarn'
      cache: true
      min-node-version: 16
      napi: true

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment: npm
    permissions:
      contents: write
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish
      - id: pkg
        run: |
          content=`cat ./package.json | tr '\n' ' '`
          echo "json=$content" >> "$GITHUB_OUTPUT"
      - run: |
          git tag v${{ fromJson(steps.pkg.outputs.json).version }}
          git push origin v${{ fromJson(steps.pkg.outputs.json).version }}
