name: Release

on:
  workflow_call:
    # secrets:
    #   npm_token:
    #     required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm
    # with:
    #   npm_token: ${{ env.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: echo ${{ secrets.REPO_TEST }}
      - run: echo ${{ secrets.NPM_TEST }}
        # env:
        #   NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
